### ISSUE TITLE
server: Incorrectly drops empty bodied headers

### ISSUE THREAD

**Issue by 56KBs** [emersion/go-milter#21]
If a header is received without a body, e.g `header-name:\r\n` the server will drop it. 

https://github.com/emersion/go-milter/blob/8790ca6f66780d86186d209d7b1e60c7ffd601be/session.go#L179-L184 Expects an array oif length two, however `decodeCStrings` result in a slice containing only one value.

For example:
header-name would be represented by `header-name\x00\x00` on the wire, following trimming the trailing null, `header-name\x00` is left, once split by the null terminator, the end result is just `["header-name"]`, instead of the expected `["header-name",""]`.

This could cause issues in the scenario of emails headers signed with DKIM that contain no value.

Additionally, this could be related to https://github.com/emersion/go-milter/pull/14 - If an MTA were to provide the last macro containing no data value, this would cause a panic as the empty value would have been dropped.

**Comment by sshort** [comment]
Created a pull request to merge 56KBs fix: https://github.com/emersion/go-milter/pull/22
