### ISSUE TITLE
v0.3.3: unable to run test: milter: negotiate: unsupported protocol version: 2

### ISSUE THREAD

**Issue by Isma399** [emersion/go-milter#29]
Hello,

I am writing a DKIM-milter (only signing), heavily inspired from :
https://github.com/emersion/go-msgauth/tree/master/cmd/dkim-milter

I am using:
-  github.com/emersion/go-milter v0.3.3
- github.com/emersion/go-msgauth v0.6.6

To be able to write test, I have started with clinet_test.go from v0.3.3
I have met this error:
```
milter: negotiate: unsupported protocol version: 2
```

I see that this value is hardcoded in server.go
I have tested to change it while instancing  Server:
```go
s := emersionMilter.Server{
                NewMilter: func() emersionMilter.Milter {
                        return &mm
                },
                Actions:  emersionMilter.OptAddHeader | emersionMilter.OptChangeHeader,
                Protocol: 0x06,
        }
```
And downgrade clientVersion with:
```go
cl := emersionMilter.NewClientWithOptions("tcp", local.Addr().String(), emersionMilter.ClientOptions{
                ActionMask: emersionMilter.OptAddHeader | emersionMilter.OptChangeHeader,
                cl := emersionMilter.NewClientWithOptions("tcp", local.Addr().String(), emersionMilter.ClientOptions{
                ActionMask: emersionMilter.OptAddHeader | emersionMilter.OptChangeHeader,
        })
        })
 ```
 
 Because of this check:
 ```go
 if milterVersion < clientProtocolVersion {
		return fmt.Errorf("milter: negotiate: unsupported protocol version: %v", milterVersion)
	}
```

But it fixed nothing..

Have you some hint to pass the test?
Should I use master branch?

Thanks

**Comment by emersion** [comment]
Yeah, please try latest commit (I justt released a new version).

**Comment by Isma399** [comment]
Thanks for being so fast!
That works now.
