### ISSUE TITLE
Question - Implementation of DKIM

### ISSUE THREAD

**Issue by abolinhas** [emersion/go-milter#33]
Hi
I'm using milter with Postfix, now i'm trying to implement DKIM using this library https://github.com/toorop/go-dkim.
My question is where I should put dkim.Sign method()? Inside Body(), BodyChunk(), Headers ()....?
Seams Dkim needs to get the full message, sign it and replace the message with a signed on.

Best regards

**Comment by emersion** [comment]
The go-msgauth package has a DKIM milter: https://github.com/emersion/go-msgauth/blob/master/cmd/dkim-milter/main.go

**Comment by abolinhas** [comment]
Thanks for you reply.
I'm testing it, but I'm encouter some issue.
Already open a new ticket.
https://github.com/emersion/go-msgauth/issues/66
