### ISSUE TITLE
Question about package stability

### ISSUE THREAD

**Issue by anhdowastaken** [emersion/go-milter#5]
I'm using libmilter of Sendmail to develop milter. Golang cgo is good but you know it has overhead.
Because of performance, I'm interested in your go-milter package. How about its stability?

Thanks!

**Comment by emersion** [comment]
Switched to Go modules and released [v0.1.0](https://github.com/emersion/go-milter/releases/tag/v0.1.0). There are a few things I'd like to change in the API before 1.0, but Go modules should ensure that won't break your builds.
